# Generated by Django 4.2.5 on 2023-10-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='admin',
        ),
    ]
